package message

type MessageKey string

func (c MessageKey) String() string {
	return string(c)
}

const (
	ErrUnsupportedFileType     MessageKey = "UNSUPPORTED_FILE_TYPE"
	ErrUnsupportedImageType    MessageKey = "UNSUPPORTED_IMAGE_TYPE"
	ErrFileTooLarge            MessageKey = "FILE_TOO_LARGE"
	ErrInvalidInput            MessageKey = "INVALID_INPUT"
	ErrAuthHeaderMissing       MessageKey = "AUTH_HEADER_MISSING"
	ErrTokenInvalid            MessageKey = "TOKEN_INVALID"
	ErrTokenNotFound           MessageKey = "TOKEN_NOT_FOUND"
	ErrTokenExpired            MessageKey = "TOKEN_EXPIRED"
	ErrInvalidClaims           MessageKey = "INVALID_CLAIMS"
	ErrInvalidIDFormat         MessageKey = "INVALID_ID_FORMAT"
	ErrUnexpectedSigningMethod MessageKey = "UNEXPECTED_SIGNING_METHOD"

	ErrCacheMiss MessageKey = "CACHE_MISS"

	ErrGenerateToken            MessageKey = "GENERATE_TOKEN"
	ErrTranslateToken           MessageKey = "TRANSLATE_TOKEN"
	ErrProcessToken             MessageKey = "PROCESS_TOKEN"
	ErrHashPassword             MessageKey = "HASH_PASSWORD"
	ErrCheckPassword            MessageKey = "CHECK_PASSWORD"
	ErrProcessUserPassword      MessageKey = "PROCESS_USER_PASSWORD"
	ErrPasswordNotMeetsCriteria MessageKey = "PASSWORD_NOT_MEETS_CRITERIA"
	ErrSendEmail                MessageKey = "SEND_EMAIL"
	ErrUploadFile               MessageKey = "UPLOAD_FILE"
	ErrDeleteFile               MessageKey = "DELETE_FILE"
	ErrUploadImage              MessageKey = "UPLOAD_IMAGE"
	ErrDeleteImage              MessageKey = "DELETE_IMAGE"
	ErrProcessImage             MessageKey = "PROCESS_IMAGE"
	ErrCreateFileSpace          MessageKey = "CREATE_FILE_SPACE"
	ErrAccessToken              MessageKey = "ACCESS_TOKEN"
	ErrRefreshToken             MessageKey = "REFRESH_TOKEN"

	ErrInvalidOAuthProvider       MessageKey = "INVALID_OAUTH_PROVIDER"
	ErrOAuthStateInvalid          MessageKey = "OAUTH_STATE_INVALID"
	ErrOAuthCodeExchange          MessageKey = "OAUTH_CODE_EXCHANGE"
	ErrOAuthUserInfo              MessageKey = "OAUTH_USER_INFO"
	ErrOAuthUserUseOAuthLogin     MessageKey = "OAUTH_USER_USE_OAUTH_LOGIN"
	ErrOAuthExisting              MessageKey = "OAUTH_EXISTING"
	ErrLinkOAuth                  MessageKey = "LINK_OAUTH"
	ErrOAuthSignUp                MessageKey = "OAUTH_SIGN_UP"
	ErrOAuthCallback              MessageKey = "OAUTH_CALLBACK"
	ErrPrepareVerificationEmail   MessageKey = "PREPARE_VERIFICATION_EMAIL"
	ErrPrepareForgotPasswordEmail MessageKey = "PREPARE_FORGOT_PASSWORD_EMAIL"

	ErrRegisterFailed        MessageKey = "REGISTER_FAILED"
	ErrLoginFailed           MessageKey = "LOGIN_FAILED"
	ErrUserNotFound          MessageKey = "USER_NOT_FOUND"
	ErrTerminateAllSessions  MessageKey = "TERMINATE_ALL_SESSIONS"
	ErrUserAlreadyExists     MessageKey = "USER_ALREADY_EXISTS"
	ErrEmailAlreadyExists    MessageKey = "EMAIL_ALREADY_EXISTS"
	ErrEmailNotVerified      MessageKey = "EMAIL_NOT_VERIFIED"
	ErrPasswordNotMatch      MessageKey = "PASSWORD_NOT_MATCH"
	ErrInvalidEmail          MessageKey = "INVALID_EMAIL"
	ErrInvalidEmailLength    MessageKey = "INVALID_EMAIL_LENGTH"
	ErrInvalidGender         MessageKey = "INVALID_GENDER"
	ErrInvalidPhone          MessageKey = "INVALID_PHONE"
	ErrUsernameAlreadyExists MessageKey = "USERNAME_ALREADY_EXISTS"
	ErrCreateUser            MessageKey = "CREATE_USER"
	ErrUpdateUser            MessageKey = "UPDATE_USER"
	ErrDeleteUser            MessageKey = "DELETE_USER"
	ErrUpdateUserStatus      MessageKey = "UPDATE_USER_STATUS"
	ErrGetAllUsers           MessageKey = "GET_ALL_USERS"
	ErrGetUserInformation    MessageKey = "GET_USER_INFORMATION"
	ErrActivateUser          MessageKey = "ACTIVATE_USER"
	ErrUpdateUserPassword    MessageKey = "UPDATE_USER_PASSWORD"

	ErrInternalServerError MessageKey = "INTERNAL_SERVER_ERROR"
	ErrInvalidRequestBody  MessageKey = "INVALID_REQUEST_BODY"
	ErrUnauthorized        MessageKey = "UNAUTHORIZED"
	ErrForbidden           MessageKey = "FORBIDDEN"
	ErrNotFound            MessageKey = "NOT_FOUND"
	ErrConflict            MessageKey = "CONFLICT"
	ErrTooManyRequests     MessageKey = "TOO_MANY_REQUESTS"
	ErrValidationFailed    MessageKey = "VALIDATION_FAILED"
	ErrLogoutFailed        MessageKey = "LOGOUT_FAILED"
	ErrVerifyEmailFailed   MessageKey = "VERIFY_EMAIL_FAILED"
	ErrResetPasswordFailed MessageKey = "RESET_PASSWORD_FAILED"
	ErrOAuthLoginFailed    MessageKey = "OAUTH_LOGIN_FAILED"
	ErrOAuthUnlinkFailed   MessageKey = "OAUTH_UNLINK_FAILED"

	LoginSuccess                  MessageKey = "LOGIN_SUCCESS"
	RegisterSuccess               MessageKey = "REGISTER_SUCCESS"
	RefreshSuccess                MessageKey = "REFRESH_SUCCESS"
	LogoutSuccess                 MessageKey = "LOGOUT_SUCCESS"
	SendVerificationEmailSuccess  MessageKey = "SEND_VERIFICATION_EMAIL_SUCCESS"
	VerifyEmailSuccess            MessageKey = "VERIFY_EMAIL_SUCCESS"
	SendResetPasswordEmailSuccess MessageKey = "SEND_RESET_PASSWORD_EMAIL_SUCCESS"
	ResetPasswordSuccess          MessageKey = "RESET_PASSWORD_SUCCESS"
	ChangePasswordSuccess         MessageKey = "CHANGE_PASSWORD_SUCCESS"
	CreateUserSuccess             MessageKey = "CREATE_USER_SUCCESS"
	UpdateUserSuccess             MessageKey = "UPDATE_USER_SUCCESS"
	ChangeUserStatusSuccess       MessageKey = "CHANGE_USER_STATUS_SUCCESS"
	GetUserInfoSuccess            MessageKey = "GET_USER_INFO_SUCCESS"
	GetAllUsersSuccess            MessageKey = "GET_ALL_USERS_SUCCESS"
	DeleteUserSuccess             MessageKey = "DELETE_USER_SUCCESS"
	OAuthLoginSuccess             MessageKey = "OAUTH_LOGIN_SUCCESS"
	OAuthCallbackSuccess          MessageKey = "OAUTH_CALLBACK_SUCCESS"
	OAuthLinkSuccess              MessageKey = "OAUTH_LINK_SUCCESS"
	OAuthUnlinkSuccess            MessageKey = "OAUTH_UNLINK_SUCCESS"
)
